In [29]:
import numpy as np

In [30]:
vectors=np.array(
    [[0,0,4],
     [0,1,1],
     [1,1,1]])

In [31]:
q1=vectors[0]

In [32]:
q1_normalized=q1/np.linalg.norm(q1)
q1_normalized

array([0., 0., 1.])

In [33]:
basis=[]
basis.append(q1_normalized)

In [34]:
q2=vectors[1]-np.dot(q1_normalized,vectors[1])*q1_normalized
if np.linalg.norm(q2)<1e-7:
    print("q2 is depent on q1")
else:
    q2_normalized = q2/np.linalg.norm(q2)
    basis.append(q2_normalized)
    q2_normalized

In [35]:
basis

[array([0., 0., 1.]), array([0., 1., 0.])]

In [36]:
q2_normalized

array([0., 1., 0.])

In [37]:
q3=vectors[2]-\
    np.dot(q1_normalized, vectors[2]) * q1_normalized - \
    np.dot(q2_normalized, vectors[2]) * q2_normalized

if np.linalg.norm(q3)<1e-7:
    print("q3 is dependent on q1 and/or q2")
else:
    q3_normalized=q3/np.linalg.norm(q3)
    basis.append(q3_normalized)
    q3_normalized

In [38]:
q3_normalized

array([1., 0., 0.])

In [39]:
def gram_schmidt(vectors):
    basis=[]
    for ai in vectors:
        qnew =ai-np.sum(np.dot(ai,qj) * qj for qj in basis )
        norm =np.linalg.norm(qnew)
        if (norm >1e-10):
            basis.append(qnew/norm)
        else:
            raise Exception(f"vector {ai} is linearly dependent on others")
    return np.array(basis)

In [40]:
gram_schmidt(vectors)

/var/folders/fx/jqp4w8917kg8hz3_gsxtf9z80000gn/T/ipykernel_3442/3851787547.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  qnew =ai-np.sum(np.dot(ai,qj) * qj for qj in basis )


array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [41]:
vectors=np.array(
    [[1,1,1],
     [0,0,4],
     [0,1,1],])
gram_schmidt(vectors)

/var/folders/fx/jqp4w8917kg8hz3_gsxtf9z80000gn/T/ipykernel_3442/3851787547.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  qnew =ai-np.sum(np.dot(ai,qj) * qj for qj in basis )


array([[ 5.77350269e-01,  5.77350269e-01,  5.77350269e-01],
       [-4.08248290e-01, -4.08248290e-01,  8.16496581e-01],
       [-7.07106781e-01,  7.07106781e-01,  3.14018492e-16]])

In [42]:
vectors=np.array(
    [[0,0,4],
     [0,0,2],
     [1,1,1]])
gram_schmidt(vectors)

/var/folders/fx/jqp4w8917kg8hz3_gsxtf9z80000gn/T/ipykernel_3442/3851787547.py:4: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  qnew =ai-np.sum(np.dot(ai,qj) * qj for qj in basis )


Exception: vector [0 0 2] is linearly dependent on others